export COBOL_PATH="/c/Program Files/gnucobol/"
echo "Assuming GnuCOBOL is installed in $COBOL_PATH"
export COB_MAIN_DIR="${COBOL_PATH}"
export COB_CONFIG_DIR="${COB_MAIN_DIR}config"
export COB_COPY_DIR="${COB_MAIN_DIR}copy"
export COB_CFLAGS="-I\"${COB_MAIN_DIR}include\" $COB_CFLAGS"
export COB_LDFLAGS="-L\"${COB_MAIN_DIR}lib\" $COB_LDFLAGS"
export COB_LIBRARY_PATH="${COB_MAIN_DIR}extras"
export PATH="${COB_MAIN_DIR}bin:$PATH"
export LOCALEDIR="${COB_MAIN_DIR}locale"
export TZDIR="${COB_MAIN_DIR}share/zoneinfo"